export const AUTHENTICATION_BEGIN = "AUTHENTICATION_BEGIN";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";

export const SIGN_OUT_BEGIN = "SIGN_OUT_BEGIN";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

export const CREATE_NEWUSER_BEGIN = "CREATE_NEWUSER_BEGIN";
export const CREATE_NEWUSER_SUCCESS = "CREATE_NEWUSER_SUCCESS";

export const SET_ERROR = "SET_ERROR";
